test:
  adapter: sqlite3
  database: db/foreman4rails
  pool: 5
  timeout: 5000
production:
  adapter: sqlite3
  database: db/foreman4rails
  pool: 5
  timeout: 5000
development:
  adapter: sqlite3
  database: db/foreman4rails
  pool: 5
  timeout: 5000