test:
  adapter: postgresql
  database: foreman4rails
  username: deploy
  pasword: 1234
production:
  adapter: postgresql
  database: foreman4rails
  username: deploy
  pasword: 1234
development:
  adapter: postgresql
  database: foreman4rails
  username: deploy
  pasword: 1234